Vagrant.configure("2") do |config|

	config.vm.box = "minimal/centos/7"
	config.vm.box_version = "7.0"
	
	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network "private_network", ip: "192.168.33.10"
	#
	config.vm.network "public_network"
	config.vm.define "HostVagrant"
        config.vm.hostname = "LVTVM01"
	#config.vm.synced_folder "./backup", "/vagrant_data", create: true

	config.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = "2"
                vb.name = "VM-TEST"
	end

	config.vm.provision "shell", inline: <<-SHELL
		yum -y install epel-release && yum -y instal python-pip
		useradd ansible	
	SHELL
end
