Vagrant.configure("2") do |config|

	config.vm.box = "centos/7"
	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network "private_network", ip: "192.168.33.10"
	  
	config.vm.network "public_network"
	#config.vm.synced_folder "./backup", "/vagrant_data", create: true

	config.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
	end

	config.vm.provision "shell", inline: <<-SHELL
		yum -y update
		yum -y install epel-release
		yum -y instal python-pip
		useradd ansible	
	SHELL
end
